# Configuration stuff
#--------------------
PERCENTAGE?=0.5

REMOTE_KNN?=true
REMOTE_KNN_SPLIT?=5
REMOTE_KNN_TIMEOUT?=100000000

KNN_CONFUSION_ARGS?=-M --knn=3 -n 1.5 -q 10
KNN_RENDER_LATEX_ARGS?=-lscxp
KNN_RENDER_RESUME_ARGS?=-r
USE_MODEL?=true
USE_SPLIT?=true
