# Configuration stuff
#--------------------
PERCENTAGE=0.5

REMOTE_KNN=true
REMOTE_KNN_SPLIT=5
REMOTE_KNN_TIMEOUT=100000000

KNN_CONFUSION_ARGS=-M --knn=3
KNN_RENDER_LATEX_ARGS=-lscxp
USE_MODEL=true
USE_SPLIT=true
