# Configuration stuff
#--------------------
PERCENTAGE?=0.5

REMOTE_KNN?=true
REMOTE_KNN_SPLIT?=5
REMOTE_KNN_TIMEOUT?=100000000

KNN_CONFUSION_ARGS?=-M --knn=1 -n 2.4 -q 12
KNN_RENDER_LATEX_ARGS?=-lscxp
KNN_RENDER_RESUME_ARGS?=-r -S
USE_MODEL?=true
USE_SPLIT?=false
